### ISSUE TITLE
Question - `GetImageBy` filename

### ISSUE THREAD

**Issue by sagesteppe** [zivankaraman/CDSE#19]
If one has to do some advanced filtering to determine which images they want to download then they are left with a vector of file names. 

```{r}
[1] "S2B_MSIL2A_20240729T174909_N0511_R141_T13SBC_20240729T214511.SAFE"
[2] "S2B_MSIL2A_20240729T174909_N0511_R141_T13SCC_20240729T214511.SAFE"
[3] "S2B_MSIL2A_20240729T174909_N0511_R141_T13SDC_20240729T214511.SAFE"
[4] "S2B_MSIL2A_20240729T174909_N0511_R141_T13SBD_20240729T214511.SAFE"
[5] "S2B_MSIL2A_20240729T174909_N0511_R141_T13SCD_20240729T214511.SAFE"
[6] "S2B_MSIL2A_20240729T174909_N0511_R141_T13SDD_20240729T214511.SAFE"
```

They may also want to still utilize the cropping functionality, and masking. How do we go about downloading this list of files, while still taking advantage of that functionality? I feel like this is supported but I am missing it in the documentation. 

```{r}
script_file <- system.file("scripts", "RawBands.js", package = "CDSE")

GetImageByBbox(
  aoi = aoi, 
  script = script_file,
  mask = TRUE, 
  collection = "sentinel-2-l2a", format = "image/tiff",
  mosaicking_order = "leastCC", resolution = 10, client = OAuthClient
  )
```

**Comment by zivankaraman** [comment]
Hi,

I'm not sure I understand your use case. It seems that all your files have
the same timestamp, representing different tiles, which makes me think your
AOI is very large.

To my knowledge, there is no way in the Sentinel-Hub process API (the one
used by the GetImage function) to target a specific "SAFE" file. You could
try to achieve the desired "advanced filtering" through clever values for
the "mosaicking_order" and "time_range" parameters, if possible.

The processing API processes pixel by pixel, and if more than one image is
available (which is NOT the case most of the time if your time range is
just one day), the parameter "mosaicking_order" defines how you choose the
image from which the pixel is taken.

Hope this helps.

Regards,
Zivan

**Comment by sagesteppe** [comment]
Hey Zivan, 

I developed an alternative approach still using CDES - I was totally over thinking it. Today is not my best day. Yes, the AOI could be considered large. 

Thanks for your time, 
Reed

P.S. Including this before closed in case any one does something as stupid as I was. Not a true reprex, but should give the idea. Essentially, identify the days of interest, subset to moderate amounts of cloud cover and then feed back into 'GetImageByAOI'. I assume this could be made parallel with mclapply, but I'm going out of town for the week so... 

```{r}
library(CDSE)
library(terra)
library(sf)

OAuthClient <- GetOAuthClient(
  id = Sys.getenv("CopernicusOAuthID"),
  secret = Sys.getenv("CopernicusOAuthSecret")
)

script_file <- system.file("scripts", "RawBands.js", package = "CDSE")
aoi <- st_as_sfc(st_bbox(template))

catalog_results <- SearchCatalog(
  aoi = aoi, 
  from = as.Date('2017-05-01'), to = as.Date('2024-08-01'),
  # first relevant flights are in 2017, a was flying in 2016,
  # but we'll just skip that year to make writing methods easier
  collection = "sentinel-2-l2a",
  client = OAuthClient
)

cr <- catalog_results |>
  mutate(Month = as.numeric(str_remove_all(str_extract(acquisitionDate, '-[0-9]{2}-'), '-'))) |>
  filter(Month >= 5, Month <= 7) |> # we want to detect late laying snow packs
  group_by(acquisitionDate) |> 
  # only bother with tiles which have good coverage on that day! No need for random tiles. 
  mutate(
    totalArea = sum(areaCoverage), 
    n = n()) |>
  filter(n > 4 & totalArea >= 100) |> 
  # NDSI cannot see through clouds, we will drop dates with
  # very high cloud cover 
  group_by(acquisitionDate) |>
  mutate(
    meanCloud = mean(tileCloudCover)
  ) |>
  filter(meanCloud <= 35) |>

  # for visualizing whether we have an OK cloud drop off time
  mutate(
    year = str_extract(acquisitionDate, '[0-9]{4}'), 
    doy = yday(acquisitionDate)
  )

ggplot() + 
  geom_point(data = cr, aes(x = doy, y = year)) 

dates <- unique(cr$acquisitionDate)
p <- '/media/steppe/hdd/Geospatial_data/Sentinel2EriogonumColoradense/'         

# we can only download 2500x2500 of cells per time. Use tiles to accomplish this. 
fname <- paste0(p, 'rawTiles', '_.tif')
template <- setValues(template, 1)
template <- disagg(template, fact = 1000)

setwd(paste0(p, 'template'))
terra::makeTiles(template, c(2500, 2500), filename = ".tif")

setwd(paste0(p, 'rawTiles'))
f <- paste0('../template/', list.files('../template/'))

aoImporter <- function(x){
  
  aoi <- sf::st_as_sfc(sf::st_bbox(terra::rast(x)))
  tileNO <- gsub('.tif', '', basename(x))
  for (i in seq_along(dates)){
    
    message('Downloading: ', dates[i]) # verbose just to keep an eye on it
    
    CDSE::GetImageByAOI(
      aoi = aoi, 
      time_range = dates[i], 
      script = script_file,
      mask = TRUE, 
      collection = "sentinel-2-l2a", 
      format = "image/tiff",
      file = paste0(tileNO, '_', dates[i], '.tif'),
      mosaicking_order = "leastCC", # LEAST CLOUD COVER. 
      resolution = 10, 
      client = OAuthClient
    )
  }
}

lapply(f, aoImporter)

```

**Comment by zivankaraman** [comment]
Hi Reed,

Thank you for the feedback and the script. Glad to learn you found the solution.

FGOS, few comments on your code.

When looking for the available images in the same period (months) for several consecutive years (seasonal images), one can use the combination of "`SeasonalTimerange`" and "`SearchCatalogByTimerange`" functions from the CDSE package, as explained in the "`Catalog by season`" paragraph of the "`UsingCDSE`" vignette. At the same time, you can also filter on cloud cover by setting the "`filter`" argument. This allows to reduce the need for post hoc filtering.

```
seasons <- SeasonalTimerange(from = "2017-05-01", to = "2024-08-01")
lst_summer_images <- lapply(seasons, SearchCatalogByTimerange, aoi = aoi,
                            collection = "sentinel-2-l2a",
                            filter = "eo:cloud_cover < 35", with_geometry = TRUE,
                            client = OAuthClient)
summer_images <- do.call(rbind, lst_summer_images)
```

There is no need to call the "`GetImageByAOI`" function in the for loop, the "`GetImage`" will do the job. But you could call the  "`GetImageByTimerange`" on the dates list, and run it in parallel, following the code explained in the "`Retrieving a series of images in a batch`" paragraph of the vignette.

Warning: when running queries in parallel, you could encounter the rate limiting policy issues: 
https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Overview/RateLimiting.html

Regards,
Zivan

**Comment by sagesteppe** [comment]
Hey Zivan, 

Another question - if you have the time. Sorry to resurrect this thread, but the question really does not seem consequential enough to have it's own. 

Thanks for clarifying that, I really should have looked more closely at [the vignette](https://zivankaraman.github.io/CDSE/articles/CDSE.html), it's one of the better vignettes out there; thank you for putting so much work into it. I was a bit too eager to try and get the data - I had the insatiable hunch that this one predictor was going to be the key independent variable in getting an excellent model (still do...).

Yes I timed out on downloads, I thought I could just keep grabbing new tokens, but that seems to mean one a month. I've refined the temporal scope, using your much more readable and effective code above. 

To avoid trying to download too much again, I have one more question. It's much more into the specifics of the Sentinel hub than just your package but... I _primarily_ want these data to generate NDSI (Normalized Difference Snow Index)  variables for identifying late laying snow packs. It seems three simple options are available.

1) Using your S2L2A _specifics script - is NDSI the "SNW" argument to this script? Based on the context of the other returned variables, it seems the goal of these data are to describe the conditions of the imagery itself, and it may implement a faster heuristic to determine snow cover? If SNW is indeed NDSI, _how do we provide this argument to the script_? Or would I just subset the script, ala the options below. 

2) Creating a local copy of this script [local copy](https://custom-scripts.sentinel-hub.com/custom-scripts/sentinel-2/ndsi/) in the CDSE/scripts directory and launch it as I would any of the others you've distributed in the package? Then it can be run through `GetStatistics` [as described here](https://zivankaraman.github.io/CDSE/articles/CDSE.html#retrieving-simple-statistics).   

```{js}
//VERSION=3
//Reference: https://earth.esa.int/web/sentinel/technical-guides/sentinel-2-msi/level-2a/algorithm

function setup() {
  return {
    input: ["B03", "B11", "B04", "B02", "dataMask"],
    output: { bands: 4 }
  };
}

function evaluatePixel(samples) {
  let val = index(samples.B03, samples.B11);

  if (val > 0.42)
    imgVals = [0, 0.8, 1, samples.dataMask];
  else
    imgVals = [2.5 * samples.B04, 2.5 * samples.B03, 2.5 * samples.B02, samples.dataMask];

  return imgVals
}
```

3) Downloading the individual bands (and one or two more for creating some other variables which I think would be very useful...)  using your RawBands.js script. Where I could specify the arguments "B03", "B11", "B04", "B02" to the argument? Or do I need to simply make a copy of the script (example below)? 

```{js}
//VERSION=3
//Subset of S2L2A raw bands for calculating NDSI, original data (no harmonization)

function setup() {
  return {
    input: [{
      bands: ["B03", "B11", "B04", "B02"],
      units: "DN"
    }],
    output: {
      id: "default",
      bands: 4,
      sampleType: SampleType.UINT16
    }
  }
}

function evaluatePixel(sample) {
    return [ sample.B02, sample.B03, sample.B04, sample.B11]
}
```

Obviously 3) will run tokens down most quickly, and 2) using `GetStatistics` would seem the least data hungry.

**Comment by zivankaraman** [comment]
Hey Reed,

No problem asking questions.

I think that the best way is to download the [script](https://custom-scripts.sentinel-hub.com/custom-scripts/sentinel-2/ndsi/) and save it locally. **You don’t have to put the script in the same folder as the ones distributed with the package; in fact, I would advise against it.** You can create a dedicated folder for your “personal” scripts and just provide the correct path to the functions that require the script. _This is probably not sufficiently clear (or not at all) from the documentation. I’ll try to improve it in the next release._ The scripts provided with the package are there to give you something to start and to run the examples. You can create your own library of scripts (or even several libraries for different projects if you wish) and use them in your work.

I didn’t quite catch your issue with the tokens, but if you are running out of credits, you can probably try to get bigger credits through your institution. I don’t know exactly how to do it with CDSE, but you can also contact [Sentinel Hub](https://www.sentinel-hub.com/) directly; they have some very affordable and quite generous plans (I used them in my previous corporate life). They have the same API (they provided it to CDSE), you would just have to change the URLs.

Finally, don’t forget that I’m a freelance consultant and that I can provide help if needed (sorry for this commercial message, but just in case :wink:).

Best,
Zivan

**Comment by sagesteppe** [comment]
Hey Zivan, 

I'll give option 2 a go, and save the script with all the other R material in the projects directory. I now understand the goal of the javascript scripts you have provided. Unfortunately no funds to help on this one; citing the package is the best I can (and will!) do. 

Cheers, 
Reed

**Comment by zivankaraman** [comment]
Thanks for citing the package :smiley:
