### ISSUE TITLE
"Invalid client" error when trying to authenticate 

### ISSUE THREAD

**Issue by MarcosSilva3** [zivankaraman/CDSE#2]
Hi
I'm trying to run the "AnimationCentralPark.R" example but I'm getting the following error message when trying to search the catalog of images:

```
Error in SearchCatalog(aoi = aoi, from = "2022-01-01", to = "2022-12-31",  : 
   
  httr2::resp_body_json(resp)[[1]]
1                   invalid_client
```

Do you know how can I solve this issue?
Thank you

**Comment by zivankaraman** [comment]
Hi,

It could be an authentication issue. Have you checked if you provided the
correct *id* and *secret*?

Can you try running this code to see if there's any error:
token = GetOAuthToken(id=id, secret=secret)

If you haven't done it already, please read the "*Before you start*"
document.

I hope this helps!

Best regards,
Zivan
