### ISSUE TITLE
NULL values for id, or secret throw an error in GetOAuthClient()

### ISSUE THREAD

**Issue by micha-silver** [zivankaraman/CDSE#9]
Minor issue:
If I call `GetOAuthClient()` with an empty string for `id` or `secret`, the function correctly opens a help page. However if **both** are NULL I get an error.

```
client <- CDSE::GetOAuthClient(NULL, NULL)
Error in if (id == "" || secret == "") { : 
  missing value where TRUE/FALSE needed
```

**Comment by zivankaraman** [comment]
Indeed, I typically get credentials from environment variables that return "" if not set, but possible undefined values could be NA or NULL. I'll add additional checks and update the GitHub.

**Comment by zivankaraman** [comment]
The updated version is now available on GitHub.
